# Generated by Django 4.2.7 on 2023-11-28 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=16)),
                ('cvv', models.CharField(max_length=4)),
                ('fecha_otorgamiento', models.DateField()),
                ('fecha_expiracion', models.DateField()),
                ('tipo', models.CharField(choices=[('debito', 'Tarjeta de debito'), ('credito', 'Tarjeta de credito')], max_length=30)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
